### ISSUE TITLE
Path error in autoload.php

### ISSUE THREAD

**Issue by nabil509** [LyraNetwork/krypton-php-sdk#1]
Hello, 

There is an error in included paths in autoload.php. 

Accordind to the autoload.php location, the code
`require(dirname(__FILE__) . '/src/LyraNetwork/Constants.php');`

will give path krypton-php-sdk/src/src/LyraNetwork/Constants.php

I recommend moving autoload.php to krypton-php-sdk root folder.

**Comment by yyoyo** [comment]
Good catch, fixed.

I keep the autoload.php file in src/ because root folder is only for docker and documentation files. all code related files should live in src/

thanks !
