### ISSUE TITLE
confusion with password and private key

### ISSUE THREAD

**Issue by lunika** [LyraNetwork/krypton-php-sdk#3]
IMHO there is too much confusion between what is a private key and a password.
In your documentation (https://payzen.io/en-EN/rest-api/card/integration/get-my-keys.html) the word password is used to define a private key (in the screenshot the password label is `private production key`).
But in the sdk there are a password and private key setters, they have a totally different behaviour and it introduces confusion.
You should maybe avoid the use of `password` word ? In a rest context it makes no sense to have a password

**Comment by yyoyo** [comment]
Yes, I'm aware of it. We have a little mess here.
V3 is using private key vocabulary, and coming version (V3.1) is using username/password.

We are moving to username/password to stick to the HTTP Basic Authentication terms.
The new SDK version (3.1, work in progress) will use only setUsername() and setPassword() methods.

By the way, we are opening a beta program for V3.1. If you are interested, please contact me.

Thanks for your feedback.
